// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Composable, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteDomainsDomainIdData, DeleteDomainsDomainIdError, DeleteDomainsDomainIdRecordsRecordIdData, DeleteDomainsDomainIdRecordsRecordIdError, DeleteDomainsDomainIdRecordsRecordIdResponse, DeleteDomainsDomainIdResponse, GetAuthSessionData, GetAuthSessionError, GetAuthSessionResponse, GetDomainsData, GetDomainsDomainIdData, GetDomainsDomainIdError, GetDomainsDomainIdRecordsData, GetDomainsDomainIdRecordsRecordIdData, GetDomainsDomainIdRecordsRecordIdError, GetDomainsDomainIdRecordsRecordIdResponse, GetDomainsDomainIdRecordsResponse, GetDomainsDomainIdResponse, GetDomainsResponse, GetNicUpdateData, GetNicUpdateError, GetNicUpdateResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostDomainsData, PostDomainsDomainIdRecordsData, PostDomainsDomainIdRecordsError, PostDomainsDomainIdRecordsResponse, PostDomainsError, PostDomainsResponse, PutDomainsDomainIdData, PutDomainsDomainIdError, PutDomainsDomainIdRecordsRecordIdData, PutDomainsDomainIdRecordsRecordIdError, PutDomainsDomainIdRecordsRecordIdResponse, PutDomainsDomainIdResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * DDNSv2 Update
 *
 * Endpoint for updating domain IP addresses using the DDNSv2 protocol.
 */
export const getNicUpdate = <TComposable extends Composable = '$fetch', DefaultT extends GetNicUpdateResponse = GetNicUpdateResponse>(options: Options<TComposable, GetNicUpdateData, GetNicUpdateResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetNicUpdateResponse | DefaultT, GetNicUpdateError, DefaultT>({ url: '/nic/update', ...options });

/**
 * User Login
 *
 * Authenticate a user with their username and password
 */
export const postAuthLogin = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLoginResponse = PostAuthLoginResponse>(options: Options<TComposable, PostAuthLoginData, PostAuthLoginResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthLoginResponse | DefaultT, PostAuthLoginError, DefaultT>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current Session
 *
 * Retrieve the current user's session information
 */
export const getAuthSession = <TComposable extends Composable = '$fetch', DefaultT extends GetAuthSessionResponse = GetAuthSessionResponse>(options: Options<TComposable, GetAuthSessionData, GetAuthSessionResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAuthSessionResponse | DefaultT, GetAuthSessionError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * Get All Domains
 *
 * Retrieve a list of all domains owned by the authenticated user.
 */
export const getDomains = <TComposable extends Composable = '$fetch', DefaultT extends GetDomainsResponse = GetDomainsResponse>(options: Options<TComposable, GetDomainsData, GetDomainsResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDomainsResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains',
    ...options
});

/**
 * Create Domain
 *
 * Create a new domain under the authenticated user's account.
 */
export const postDomains = <TComposable extends Composable = '$fetch', DefaultT extends PostDomainsResponse = PostDomainsResponse>(options: Options<TComposable, PostDomainsData, PostDomainsResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostDomainsResponse | DefaultT, PostDomainsError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Domain
 *
 * Delete a specific domain owned by the authenticated user.
 */
export const deleteDomainsDomainId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteDomainsDomainIdResponse = DeleteDomainsDomainIdResponse>(options: Options<TComposable, DeleteDomainsDomainIdData, DeleteDomainsDomainIdResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteDomainsDomainIdResponse | DefaultT, DeleteDomainsDomainIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}',
    ...options
});

/**
 * Get Domain
 *
 * Retrieve details of a specific domain owned by the authenticated user.
 */
export const getDomainsDomainId = <TComposable extends Composable = '$fetch', DefaultT extends GetDomainsDomainIdResponse = GetDomainsDomainIdResponse>(options: Options<TComposable, GetDomainsDomainIdData, GetDomainsDomainIdResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDomainsDomainIdResponse | DefaultT, GetDomainsDomainIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}',
    ...options
});

/**
 * Update Domain
 *
 * Update details of a specific domain owned by the authenticated user.
 */
export const putDomainsDomainId = <TComposable extends Composable = '$fetch', DefaultT extends PutDomainsDomainIdResponse = PutDomainsDomainIdResponse>(options: Options<TComposable, PutDomainsDomainIdData, PutDomainsDomainIdResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutDomainsDomainIdResponse | DefaultT, PutDomainsDomainIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get All DNS Records for Domain
 *
 * Retrieve a list of all additional DNS records for the specified domain owned by the authenticated user.
 */
export const getDomainsDomainIdRecords = <TComposable extends Composable = '$fetch', DefaultT extends GetDomainsDomainIdRecordsResponse = GetDomainsDomainIdRecordsResponse>(options: Options<TComposable, GetDomainsDomainIdRecordsData, GetDomainsDomainIdRecordsResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDomainsDomainIdRecordsResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}/records',
    ...options
});

/**
 * Create DNS Record for Domain
 *
 * Create a new additional DNS record for the specified domain owned by the authenticated user.
 */
export const postDomainsDomainIdRecords = <TComposable extends Composable = '$fetch', DefaultT extends PostDomainsDomainIdRecordsResponse = PostDomainsDomainIdRecordsResponse>(options: Options<TComposable, PostDomainsDomainIdRecordsData, PostDomainsDomainIdRecordsResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostDomainsDomainIdRecordsResponse | DefaultT, PostDomainsDomainIdRecordsError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}/records',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete DNS Record
 *
 * Delete a specific additional DNS record for the specified domain owned by the authenticated user.
 */
export const deleteDomainsDomainIdRecordsRecordId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteDomainsDomainIdRecordsRecordIdResponse = DeleteDomainsDomainIdRecordsRecordIdResponse>(options: Options<TComposable, DeleteDomainsDomainIdRecordsRecordIdData, DeleteDomainsDomainIdRecordsRecordIdResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteDomainsDomainIdRecordsRecordIdResponse | DefaultT, DeleteDomainsDomainIdRecordsRecordIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}/records/{recordID}',
    ...options
});

/**
 * Get DNS Record
 *
 * Retrieve details of a specific additional DNS record for the specified domain owned by the authenticated user.
 */
export const getDomainsDomainIdRecordsRecordId = <TComposable extends Composable = '$fetch', DefaultT extends GetDomainsDomainIdRecordsRecordIdResponse = GetDomainsDomainIdRecordsRecordIdResponse>(options: Options<TComposable, GetDomainsDomainIdRecordsRecordIdData, GetDomainsDomainIdRecordsRecordIdResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDomainsDomainIdRecordsRecordIdResponse | DefaultT, GetDomainsDomainIdRecordsRecordIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}/records/{recordID}',
    ...options
});

/**
 * Update DNS Record
 *
 * Update a specific additional DNS record for the specified domain owned by the authenticated user.
 */
export const putDomainsDomainIdRecordsRecordId = <TComposable extends Composable = '$fetch', DefaultT extends PutDomainsDomainIdRecordsRecordIdResponse = PutDomainsDomainIdRecordsRecordIdResponse>(options: Options<TComposable, PutDomainsDomainIdRecordsRecordIdData, PutDomainsDomainIdRecordsRecordIdResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutDomainsDomainIdRecordsRecordIdResponse | DefaultT, PutDomainsDomainIdRecordsRecordIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domainID}/records/{recordID}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
